NUMPY

In [41]:
pip install numpy 


In [12]:
import numpy as np

arr1 = np.array([[1,2,3], 
                 [2,3,4] , 
                 [4,5,6]])
print(arr1) 
arr1.shape 
arr1.ndim

[[1 2 3]
 [2 3 4]
 [4 5 6]]


2

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.ones((3,4)) #Array of all ones


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros((1,4)) #Array of all zeros

In [ ]:
np.eye(3) #Identity Matrix

In [31]:
#Attributes of the numpy array 
arr2 =  np.array([[1,2,3,4] , [2,3,4,5]])

print("Array \n" , arr2)
print("array dimension =" , arr2.ndim )
print("number of elements in the arr2 = ",arr2.size)
print("shape of the array = " , arr2.shape)
print("data type of the array = " , arr2.dtype)


Array 
 [[1 2 3 4]
 [2 3 4 5]]
array dimension = 2
number of elements in the arr2 =  8
shape of the array =  (2, 4)
data type of the array =  int64


In [32]:
##numpy  vectorized operations 

a = np.array([1,2,3,4])
b =np.array([5,6,7,8])

print("Addition = " , a + b)
print("Subtraction = " , a - b)
print("Multiplication = " , a * b)
print("Division = " , a / b)
print("Exponentiation = " , a ** 2)
print("Square Root = " , np.sqrt(a))
print("Sin values = " , np.sin(a))
print("Cos values = " , np.cos(a))
print("Log values = " , np.log(a))
print("Dot Product = " , np.dot(a,b))

Addition =  [ 6  8 10 12]
Subtraction =  [-4 -4 -4 -4]
Multiplication =  [ 5 12 21 32]
Division =  [0.2        0.33333333 0.42857143 0.5       ]
Exponentiation =  [ 1  4  9 16]
Square Root =  [1.         1.41421356 1.73205081 2.        ]
Sin values =  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Cos values =  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
Log values =  [0.         0.69314718 1.09861229 1.38629436]
Dot Product =  70


In [36]:
#array Slicing and indexing 
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10], 
                [11,12,13,14,15]])
print("array:\n", arr)
arr[0][4]  #Accessing element at first row and fifth column

array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


np.int64(5)

In [ ]:
arr[1:2 , 2:4]  #Slicing the array to get sub array 

array([[8, 9]])

In [39]:
##statstical concepts - Normalization 

data = np.array([10, 12, 15, 18, 20, 22, 25])

mean = np.mean(data)
std_dev = np.std(data)

print(mean)
print(std_dev)

normalized_data =(data -mean) / std_dev
print("Normalization result = ", normalized_data)

17.428571428571427
5.010193690500052
Normalization result =  [-1.48269147 -1.0835053  -0.48472606  0.11405319  0.51323935  0.91242552
  1.51120476]


In [40]:
#mean
data = np.array([10, 12, 15, 18, 20, 22, 25]) 
mean = np.mean(data)
std_dev = np.std(data)
varience = np.var(data)

print("Mean = " , mean)
print("Standard Deviation = " , std_dev)
print("Varience = " , varience)

Mean =  17.428571428571427
Standard Deviation =  5.010193690500052
Varience =  25.102040816326532


In [43]:
#Logical operation 
arr = np.array([10, 15, 20, 25, 30])
arr > 20 #Elements greater than 20


array([False, False, False,  True,  True])

In [4]:
import pandas as pd
df = pd.read_csv('data.csv')  #Reading a CSV file into a DataFrame
print(df.head(10))  #Displaying the first few rows of the DataFrame

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West
